algoritmo "ex1"
// Função :
// Autor : gustavo pimentel
// Data : 08/11/2022
// Seção de Declarações 
var
contador,soma:inteiro
numeros:vetor[1..10]de inteiro
inicio

para contador de 1 ate 10 faca
    numeros[contador]<- randi(10)
    escreva(numeros[contador])
    soma<-soma+(numeros[contador])
fimpara
escreval
escreval("a soma de todos os números:",soma)

inicio
// Seção de Comandos 
fimalgoritmo
